import {
  BookOpen,
  Calculator,
  Factory,
  FileChartColumn,
  Grid3X3,
  LayoutDashboard,
  Notebook,
  Package,
  RotateCcw,
  ShoppingBag,
  Truck,
  UserCogIcon,
  Users,
  Settings,
} from 'lucide-vue-next'
import type { IMenuItem } from '~/types/menu.type'

export const MOCK_MENU: IMenuItem[] = [
  {
    id: 1,
    label: 'Dashboard',
    path: '/',
    icon: LayoutDashboard,
    type: 'item',
    mobile: true,
  },
  {
    id: 2,
    label: 'Inventario',
    path: '/inventario',
    icon: Package,
    type: 'item',
    mobile: true,
  },
  {
    id: 3,
    label: 'Recetas',
    path: '/recetas',
    icon: BookOpen,
    type: 'item',
  },
  {
    id: 4,
    label: 'Produccion',
    path: '/produccion',
    icon: Factory,
    type: 'item',
  },
  {
    id: 5,
    label: 'Productos',
    path: '/productos',
    icon: ShoppingBag,
    type: 'item',
    mobile: true,
  },
  {
    id: 6,
    label: 'Charolas',
    path: '/charolas',
    icon: Grid3X3,
    type: 'item',
    mobile: true,
  },
  {
    id: 7,
    label: 'Entregas',
    path: '/entregas',
    icon: Truck,
    type: 'item',
  },
  {
    id: 8,
    label: 'Devoluciones',
    path: '/devoluciones',
    icon: RotateCcw,
    type: 'item',
  },
  {
    id: 9,
    label: 'Administracion',
    path: '/administracion',
    icon: UserCogIcon,
    type: 'group',
    children: [
      {
        id: 10,
        label: 'Contabilidad',
        path: '/contabilidad',
        type: 'item',
        icon: Calculator,
      },
      {
        id: 11,
        label: 'Reportes',
        path: '/reportes',
        type: 'item',
        icon: FileChartColumn,
      },
    ],
  },
  {
    id: 12,
    label: 'Catalogos',
    path: '/catalogos',
    icon: Notebook,
    type: 'group',
    children: [
      {
        id: 13,
        label: 'Clientes',
        path: '/clientes',
        type: 'item',
        icon: Users,
      },
      {
        id: 14,
        label: 'Usuarios',
        path: '/usuarios',
        type: 'item',
        icon: Users,
      },
    ],
  },
  {
    id: 13,
    label: 'Configuracion',
    path: '/configuracion',
    icon: Settings,
    type: 'item',
    mobile: true,
  },
]
